[package]
name = "hello_relly"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
zerocopy = "0.3"
bincode = "1.3"
tempfile = "3"
md-5 = "0.9"
